import asyncio
import grpc
from lastmile.v1 import user_pb2, user_pb2_grpc, common_pb2
from common.run import serve
from common.db import get_db

class UserServer(user_pb2_grpc.UserServiceServicer):
    def __init__(self):
        self.db = get_db()
        self.users = self.db.users

    async def CreateUser(self, request, context):
        print(f"[user] CreateUser request={request}")
        u = request.user
        # Auto-generate ID if not provided, or use provided one (though user asked for auto-gen, client might send one if we don't change it. 
        # But the prompt said "do not ask rider_id or driver_id they should be auto generated by monogodb itself".
        # So we should probably ignore the ID sent by client if it's empty, or even if it's not.
        # Let's generate a new ObjectId and use its string representation.
        
        # However, for simplicity and to match the proto which expects string ID, we can use ObjectId str.
        # We also need to store password.
        
        user_doc = {
            "role": u.role,
            "name": u.name,
            "phone": u.phone,
            "password": request.password
        }
        result = self.users.insert_one(user_doc)
        uid = str(result.inserted_id)
        
        # Update the doc with the ID string for easier retrieval if needed, or just construct the response
        nu = common_pb2.User(id=uid, role=u.role, name=u.name, phone=u.phone)
        return user_pb2.CreateUserResponse(user=nu)

    async def GetUser(self, request, context):
        print(f"[user] GetUser request={request}")
        from bson.objectid import ObjectId
        try:
            oid = ObjectId(request.id)
            doc = self.users.find_one({"_id": oid})
        except:
            doc = None
            
        if not doc:
             # Fallback: maybe it was stored as string ID?
             doc = self.users.find_one({"_id": request.id})

        if doc:
            u = common_pb2.User(
                id=str(doc["_id"]),
                role=doc["role"],
                name=doc["name"],
                phone=doc["phone"],
            )
            return user_pb2.GetUserResponse(user=u)
        return user_pb2.GetUserResponse()

    async def Authenticate(self, request, context):
        print(f"[user] Authenticate request={request}")
        # Find by phone
        doc = self.users.find_one({"phone": request.phone})
        if doc and doc["password"] == request.password:
            return user_pb2.AuthenticateResponse(user_id=str(doc["_id"]), jwt="demo-jwt")
        return user_pb2.AuthenticateResponse()

def factory():
    server = grpc.aio.server()
    user_pb2_grpc.add_UserServiceServicer_to_server(UserServer(), server)
    return server

if __name__ == "__main__":
    serve(factory, "[::]:50051")
