# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lastmile/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lastmile/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18lastmile/v1/common.proto\x12\x0blastmile.v1\"\x07\n\x05\x45mpty\"\"\n\x06LatLng\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\"P\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1f\n\x04role\x18\x02 \x01(\x0e\x32\x11.lastmile.v1.Role\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"`\n\x07Station\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12%\n\x08location\x18\x03 \x01(\x0b\x32\x13.lastmile.v1.LatLng\x12\x14\n\x0cnearby_areas\x18\x04 \x03(\t\"u\n\x0cRiderRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08rider_id\x18\x02 \x01(\t\x12\x12\n\nstation_id\x18\x03 \x01(\t\x12\x10\n\x08\x65ta_unix\x18\x04 \x01(\x03\x12\x11\n\tdest_area\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\"n\n\x04Trip\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\x12\x11\n\trider_ids\x18\x03 \x03(\t\x12\x10\n\x08route_id\x18\x04 \x01(\t\x12\x12\n\nstation_id\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t*3\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\t\n\x05RIDER\x10\x01\x12\n\n\x06\x44RIVER\x10\x02\x42?Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lastmile.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1'
  _globals['_ROLE']._serialized_start=497
  _globals['_ROLE']._serialized_end=548
  _globals['_EMPTY']._serialized_start=41
  _globals['_EMPTY']._serialized_end=48
  _globals['_LATLNG']._serialized_start=50
  _globals['_LATLNG']._serialized_end=84
  _globals['_USER']._serialized_start=86
  _globals['_USER']._serialized_end=166
  _globals['_STATION']._serialized_start=168
  _globals['_STATION']._serialized_end=264
  _globals['_RIDERREQUEST']._serialized_start=266
  _globals['_RIDERREQUEST']._serialized_end=383
  _globals['_TRIP']._serialized_start=385
  _globals['_TRIP']._serialized_end=495
# @@protoc_insertion_point(module_scope)
