# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lastmile.v1 import driver_pb2 as lastmile_dot_v1_dot_driver__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lastmile/v1/driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterRoute = channel.unary_unary(
                '/lastmile.v1.DriverService/RegisterRoute',
                request_serializer=lastmile_dot_v1_dot_driver__pb2.RegisterRouteRequest.SerializeToString,
                response_deserializer=lastmile_dot_v1_dot_driver__pb2.RegisterRouteResponse.FromString,
                _registered_method=True)
        self.UpdateSeats = channel.unary_unary(
                '/lastmile.v1.DriverService/UpdateSeats',
                request_serializer=lastmile_dot_v1_dot_driver__pb2.UpdateSeatsRequest.SerializeToString,
                response_deserializer=lastmile_dot_v1_dot_driver__pb2.UpdateSeatsResponse.FromString,
                _registered_method=True)
        self.GetRoute = channel.unary_unary(
                '/lastmile.v1.DriverService/GetRoute',
                request_serializer=lastmile_dot_v1_dot_driver__pb2.GetRouteRequest.SerializeToString,
                response_deserializer=lastmile_dot_v1_dot_driver__pb2.GetRouteResponse.FromString,
                _registered_method=True)
        self.DeleteRoute = channel.unary_unary(
                '/lastmile.v1.DriverService/DeleteRoute',
                request_serializer=lastmile_dot_v1_dot_driver__pb2.DeleteRouteRequest.SerializeToString,
                response_deserializer=lastmile_dot_v1_dot_driver__pb2.DeleteRouteResponse.FromString,
                _registered_method=True)


class DriverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSeats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRoute,
                    request_deserializer=lastmile_dot_v1_dot_driver__pb2.RegisterRouteRequest.FromString,
                    response_serializer=lastmile_dot_v1_dot_driver__pb2.RegisterRouteResponse.SerializeToString,
            ),
            'UpdateSeats': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSeats,
                    request_deserializer=lastmile_dot_v1_dot_driver__pb2.UpdateSeatsRequest.FromString,
                    response_serializer=lastmile_dot_v1_dot_driver__pb2.UpdateSeatsResponse.SerializeToString,
            ),
            'GetRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoute,
                    request_deserializer=lastmile_dot_v1_dot_driver__pb2.GetRouteRequest.FromString,
                    response_serializer=lastmile_dot_v1_dot_driver__pb2.GetRouteResponse.SerializeToString,
            ),
            'DeleteRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRoute,
                    request_deserializer=lastmile_dot_v1_dot_driver__pb2.DeleteRouteRequest.FromString,
                    response_serializer=lastmile_dot_v1_dot_driver__pb2.DeleteRouteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lastmile.v1.DriverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lastmile.v1.DriverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.v1.DriverService/RegisterRoute',
            lastmile_dot_v1_dot_driver__pb2.RegisterRouteRequest.SerializeToString,
            lastmile_dot_v1_dot_driver__pb2.RegisterRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSeats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.v1.DriverService/UpdateSeats',
            lastmile_dot_v1_dot_driver__pb2.UpdateSeatsRequest.SerializeToString,
            lastmile_dot_v1_dot_driver__pb2.UpdateSeatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.v1.DriverService/GetRoute',
            lastmile_dot_v1_dot_driver__pb2.GetRouteRequest.SerializeToString,
            lastmile_dot_v1_dot_driver__pb2.GetRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.v1.DriverService/DeleteRoute',
            lastmile_dot_v1_dot_driver__pb2.DeleteRouteRequest.SerializeToString,
            lastmile_dot_v1_dot_driver__pb2.DeleteRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
