# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lastmile/v1/location.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lastmile/v1/location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lastmile.v1 import common_pb2 as lastmile_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1alastmile/v1/location.proto\x12\x0blastmile.v1\x1a\x18lastmile/v1/common.proto\"j\n\x0e\x44riverLocation\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\"\n\x05point\x18\x02 \x01(\x0b\x32\x13.lastmile.v1.LatLng\x12\x0f\n\x07ts_unix\x18\x03 \x01(\x03\x12\x10\n\x08route_id\x18\x04 \x01(\t\"\x1f\n\x11LocationStreamAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x32h\n\x0fLocationService\x12U\n\x14StreamDriverLocation\x12\x1b.lastmile.v1.DriverLocation\x1a\x1e.lastmile.v1.LocationStreamAck(\x01\x42?Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lastmile.v1.location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1'
  _globals['_DRIVERLOCATION']._serialized_start=69
  _globals['_DRIVERLOCATION']._serialized_end=175
  _globals['_LOCATIONSTREAMACK']._serialized_start=177
  _globals['_LOCATIONSTREAMACK']._serialized_end=208
  _globals['_LOCATIONSERVICE']._serialized_start=210
  _globals['_LOCATIONSERVICE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
