# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lastmile/v1/matching.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lastmile/v1/matching.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1alastmile/v1/matching.proto\x12\x0blastmile.v1\"d\n\x0fTryMatchRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x10\n\x08route_id\x18\x02 \x01(\t\x12\x12\n\nstation_id\x18\x03 \x01(\t\x12\x18\n\x10\x61rrival_eta_unix\x18\x04 \x01(\x03\"8\n\nAssignment\x12\x18\n\x10rider_request_id\x18\x01 \x01(\t\x12\x10\n\x08rider_id\x18\x02 \x01(\t\"j\n\x10TryMatchResponse\x12\x0f\n\x07trip_id\x18\x01 \x01(\t\x12,\n\x0b\x61ssignments\x18\x02 \x03(\x0b\x32\x17.lastmile.v1.Assignment\x12\x17\n\x0fseats_remaining\x18\x03 \x01(\x05\x32Z\n\x0fMatchingService\x12G\n\x08TryMatch\x12\x1c.lastmile.v1.TryMatchRequest\x1a\x1d.lastmile.v1.TryMatchResponseB?Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lastmile.v1.matching_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1'
  _globals['_TRYMATCHREQUEST']._serialized_start=43
  _globals['_TRYMATCHREQUEST']._serialized_end=143
  _globals['_ASSIGNMENT']._serialized_start=145
  _globals['_ASSIGNMENT']._serialized_end=201
  _globals['_TRYMATCHRESPONSE']._serialized_start=203
  _globals['_TRYMATCHRESPONSE']._serialized_end=309
  _globals['_MATCHINGSERVICE']._serialized_start=311
  _globals['_MATCHINGSERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
