# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lastmile/v1/notification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lastmile/v1/notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1elastmile/v1/notification.proto\x12\x0blastmile.v1\".\n\nPushTarget\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\"g\n\x0bPushRequest\x12(\n\x07targets\x18\x01 \x03(\x0b\x32\x17.lastmile.v1.PushTarget\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x11\n\tdata_json\x18\x04 \x01(\t\"2\n\x0cPushResponse\x12\x11\n\tattempted\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x05\x32R\n\x13NotificationService\x12;\n\x04Push\x12\x18.lastmile.v1.PushRequest\x1a\x19.lastmile.v1.PushResponseB?Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lastmile.v1.notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1'
  _globals['_PUSHTARGET']._serialized_start=47
  _globals['_PUSHTARGET']._serialized_end=93
  _globals['_PUSHREQUEST']._serialized_start=95
  _globals['_PUSHREQUEST']._serialized_end=198
  _globals['_PUSHRESPONSE']._serialized_start=200
  _globals['_PUSHRESPONSE']._serialized_end=250
  _globals['_NOTIFICATIONSERVICE']._serialized_start=252
  _globals['_NOTIFICATIONSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
