# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lastmile/v1/rider.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lastmile/v1/rider.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lastmile.v1 import common_pb2 as lastmile_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17lastmile/v1/rider.proto\x12\x0blastmile.v1\x1a\x18lastmile/v1/common.proto\"?\n\x11\x41\x64\x64RequestRequest\x12*\n\x07request\x18\x01 \x01(\x0b\x32\x19.lastmile.v1.RiderRequest\"@\n\x12\x41\x64\x64RequestResponse\x12*\n\x07request\x18\x01 \x01(\x0b\x32\x19.lastmile.v1.RiderRequest\"n\n\x1bListPendingAtStationRequest\x12\x12\n\nstation_id\x18\x01 \x01(\t\x12\x10\n\x08now_unix\x18\x02 \x01(\x03\x12\x16\n\x0eminutes_window\x18\x03 \x01(\x05\x12\x11\n\tdest_area\x18\x04 \x01(\t\"K\n\x1cListPendingAtStationResponse\x12+\n\x08requests\x18\x01 \x03(\x0b\x32\x19.lastmile.v1.RiderRequest\";\n\x13MarkAssignedRequest\x12\x13\n\x0brequest_ids\x18\x01 \x03(\t\x12\x0f\n\x07trip_id\x18\x02 \x01(\t\"\'\n\x14MarkAssignedResponse\x12\x0f\n\x07updated\x18\x01 \x01(\x05\x32\x9f\x02\n\x0cRiderService\x12M\n\nAddRequest\x12\x1e.lastmile.v1.AddRequestRequest\x1a\x1f.lastmile.v1.AddRequestResponse\x12k\n\x14ListPendingAtStation\x12(.lastmile.v1.ListPendingAtStationRequest\x1a).lastmile.v1.ListPendingAtStationResponse\x12S\n\x0cMarkAssigned\x12 .lastmile.v1.MarkAssignedRequest\x1a!.lastmile.v1.MarkAssignedResponseB?Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lastmile.v1.rider_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1'
  _globals['_ADDREQUESTREQUEST']._serialized_start=66
  _globals['_ADDREQUESTREQUEST']._serialized_end=129
  _globals['_ADDREQUESTRESPONSE']._serialized_start=131
  _globals['_ADDREQUESTRESPONSE']._serialized_end=195
  _globals['_LISTPENDINGATSTATIONREQUEST']._serialized_start=197
  _globals['_LISTPENDINGATSTATIONREQUEST']._serialized_end=307
  _globals['_LISTPENDINGATSTATIONRESPONSE']._serialized_start=309
  _globals['_LISTPENDINGATSTATIONRESPONSE']._serialized_end=384
  _globals['_MARKASSIGNEDREQUEST']._serialized_start=386
  _globals['_MARKASSIGNEDREQUEST']._serialized_end=445
  _globals['_MARKASSIGNEDRESPONSE']._serialized_start=447
  _globals['_MARKASSIGNEDRESPONSE']._serialized_end=486
  _globals['_RIDERSERVICE']._serialized_start=489
  _globals['_RIDERSERVICE']._serialized_end=776
# @@protoc_insertion_point(module_scope)
