# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lastmile/v1/station.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lastmile/v1/station.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lastmile.v1 import common_pb2 as lastmile_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19lastmile/v1/station.proto\x12\x0blastmile.v1\x1a\x18lastmile/v1/common.proto\"=\n\x14UpsertStationRequest\x12%\n\x07station\x18\x01 \x01(\x0b\x32\x14.lastmile.v1.Station\">\n\x15UpsertStationResponse\x12%\n\x07station\x18\x01 \x01(\x0b\x32\x14.lastmile.v1.Station\"\x1f\n\x11GetStationRequest\x12\n\n\x02id\x18\x01 \x01(\t\";\n\x12GetStationResponse\x12%\n\x07station\x18\x01 \x01(\x0b\x32\x14.lastmile.v1.Station\">\n\x14ListStationsResponse\x12&\n\x08stations\x18\x01 \x03(\x0b\x32\x14.lastmile.v1.Station\"+\n\x13NearbyAreasResponse\x12\x14\n\x0cnearby_areas\x18\x01 \x03(\t2\xcf\x02\n\x0eStationService\x12V\n\rUpsertStation\x12!.lastmile.v1.UpsertStationRequest\x1a\".lastmile.v1.UpsertStationResponse\x12M\n\nGetStation\x12\x1e.lastmile.v1.GetStationRequest\x1a\x1f.lastmile.v1.GetStationResponse\x12\x45\n\x0cListStations\x12\x12.lastmile.v1.Empty\x1a!.lastmile.v1.ListStationsResponse\x12O\n\x0bNearbyAreas\x12\x1e.lastmile.v1.GetStationRequest\x1a .lastmile.v1.NearbyAreasResponseB?Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lastmile.v1.station_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1'
  _globals['_UPSERTSTATIONREQUEST']._serialized_start=68
  _globals['_UPSERTSTATIONREQUEST']._serialized_end=129
  _globals['_UPSERTSTATIONRESPONSE']._serialized_start=131
  _globals['_UPSERTSTATIONRESPONSE']._serialized_end=193
  _globals['_GETSTATIONREQUEST']._serialized_start=195
  _globals['_GETSTATIONREQUEST']._serialized_end=226
  _globals['_GETSTATIONRESPONSE']._serialized_start=228
  _globals['_GETSTATIONRESPONSE']._serialized_end=287
  _globals['_LISTSTATIONSRESPONSE']._serialized_start=289
  _globals['_LISTSTATIONSRESPONSE']._serialized_end=351
  _globals['_NEARBYAREASRESPONSE']._serialized_start=353
  _globals['_NEARBYAREASRESPONSE']._serialized_end=396
  _globals['_STATIONSERVICE']._serialized_start=399
  _globals['_STATIONSERVICE']._serialized_end=734
# @@protoc_insertion_point(module_scope)
