# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lastmile.v1 import common_pb2 as lastmile_dot_v1_dot_common__pb2
from lastmile.v1 import station_pb2 as lastmile_dot_v1_dot_station__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lastmile/v1/station_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertStation = channel.unary_unary(
                '/lastmile.v1.StationService/UpsertStation',
                request_serializer=lastmile_dot_v1_dot_station__pb2.UpsertStationRequest.SerializeToString,
                response_deserializer=lastmile_dot_v1_dot_station__pb2.UpsertStationResponse.FromString,
                _registered_method=True)
        self.GetStation = channel.unary_unary(
                '/lastmile.v1.StationService/GetStation',
                request_serializer=lastmile_dot_v1_dot_station__pb2.GetStationRequest.SerializeToString,
                response_deserializer=lastmile_dot_v1_dot_station__pb2.GetStationResponse.FromString,
                _registered_method=True)
        self.ListStations = channel.unary_unary(
                '/lastmile.v1.StationService/ListStations',
                request_serializer=lastmile_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=lastmile_dot_v1_dot_station__pb2.ListStationsResponse.FromString,
                _registered_method=True)
        self.NearbyAreas = channel.unary_unary(
                '/lastmile.v1.StationService/NearbyAreas',
                request_serializer=lastmile_dot_v1_dot_station__pb2.GetStationRequest.SerializeToString,
                response_deserializer=lastmile_dot_v1_dot_station__pb2.NearbyAreasResponse.FromString,
                _registered_method=True)


class StationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpsertStation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NearbyAreas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertStation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertStation,
                    request_deserializer=lastmile_dot_v1_dot_station__pb2.UpsertStationRequest.FromString,
                    response_serializer=lastmile_dot_v1_dot_station__pb2.UpsertStationResponse.SerializeToString,
            ),
            'GetStation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStation,
                    request_deserializer=lastmile_dot_v1_dot_station__pb2.GetStationRequest.FromString,
                    response_serializer=lastmile_dot_v1_dot_station__pb2.GetStationResponse.SerializeToString,
            ),
            'ListStations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStations,
                    request_deserializer=lastmile_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=lastmile_dot_v1_dot_station__pb2.ListStationsResponse.SerializeToString,
            ),
            'NearbyAreas': grpc.unary_unary_rpc_method_handler(
                    servicer.NearbyAreas,
                    request_deserializer=lastmile_dot_v1_dot_station__pb2.GetStationRequest.FromString,
                    response_serializer=lastmile_dot_v1_dot_station__pb2.NearbyAreasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lastmile.v1.StationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lastmile.v1.StationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpsertStation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.v1.StationService/UpsertStation',
            lastmile_dot_v1_dot_station__pb2.UpsertStationRequest.SerializeToString,
            lastmile_dot_v1_dot_station__pb2.UpsertStationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.v1.StationService/GetStation',
            lastmile_dot_v1_dot_station__pb2.GetStationRequest.SerializeToString,
            lastmile_dot_v1_dot_station__pb2.GetStationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.v1.StationService/ListStations',
            lastmile_dot_v1_dot_common__pb2.Empty.SerializeToString,
            lastmile_dot_v1_dot_station__pb2.ListStationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NearbyAreas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.v1.StationService/NearbyAreas',
            lastmile_dot_v1_dot_station__pb2.GetStationRequest.SerializeToString,
            lastmile_dot_v1_dot_station__pb2.NearbyAreasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
