# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lastmile/v1/trip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lastmile/v1/trip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lastmile.v1 import common_pb2 as lastmile_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16lastmile/v1/trip.proto\x12\x0blastmile.v1\x1a\x18lastmile/v1/common.proto\"_\n\x11\x43reateTripRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x11\n\trider_ids\x18\x02 \x03(\t\x12\x10\n\x08route_id\x18\x03 \x01(\t\x12\x12\n\nstation_id\x18\x04 \x01(\t\"5\n\x12\x43reateTripResponse\x12\x1f\n\x04trip\x18\x01 \x01(\x0b\x32\x11.lastmile.v1.Trip\":\n\x17UpdateTripStatusRequest\x12\x0f\n\x07trip_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\";\n\x18UpdateTripStatusResponse\x12\x1f\n\x04trip\x18\x01 \x01(\x0b\x32\x11.lastmile.v1.Trip2\xbd\x01\n\x0bTripService\x12M\n\nCreateTrip\x12\x1e.lastmile.v1.CreateTripRequest\x1a\x1f.lastmile.v1.CreateTripResponse\x12_\n\x10UpdateTripStatus\x12$.lastmile.v1.UpdateTripStatusRequest\x1a%.lastmile.v1.UpdateTripStatusResponseB?Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lastmile.v1.trip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1'
  _globals['_CREATETRIPREQUEST']._serialized_start=65
  _globals['_CREATETRIPREQUEST']._serialized_end=160
  _globals['_CREATETRIPRESPONSE']._serialized_start=162
  _globals['_CREATETRIPRESPONSE']._serialized_end=215
  _globals['_UPDATETRIPSTATUSREQUEST']._serialized_start=217
  _globals['_UPDATETRIPSTATUSREQUEST']._serialized_end=275
  _globals['_UPDATETRIPSTATUSRESPONSE']._serialized_start=277
  _globals['_UPDATETRIPSTATUSRESPONSE']._serialized_end=336
  _globals['_TRIPSERVICE']._serialized_start=339
  _globals['_TRIPSERVICE']._serialized_end=528
# @@protoc_insertion_point(module_scope)
