# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lastmile/v1/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lastmile/v1/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lastmile.v1 import common_pb2 as lastmile_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16lastmile/v1/user.proto\x12\x0blastmile.v1\x1a\x18lastmile/v1/common.proto\"F\n\x11\x43reateUserRequest\x12\x1f\n\x04user\x18\x01 \x01(\x0b\x32\x11.lastmile.v1.User\x12\x10\n\x08password\x18\x02 \x01(\t\"5\n\x12\x43reateUserResponse\x12\x1f\n\x04user\x18\x01 \x01(\x0b\x32\x11.lastmile.v1.User\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x0fGetUserResponse\x12\x1f\n\x04user\x18\x01 \x01(\x0b\x32\x11.lastmile.v1.User\"6\n\x13\x41uthenticateRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"4\n\x14\x41uthenticateResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0b\n\x03jwt\x18\x02 \x01(\t2\xf7\x01\n\x0bUserService\x12M\n\nCreateUser\x12\x1e.lastmile.v1.CreateUserRequest\x1a\x1f.lastmile.v1.CreateUserResponse\x12\x44\n\x07GetUser\x12\x1b.lastmile.v1.GetUserRequest\x1a\x1c.lastmile.v1.GetUserResponse\x12S\n\x0c\x41uthenticate\x12 .lastmile.v1.AuthenticateRequest\x1a!.lastmile.v1.AuthenticateResponseB?Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lastmile.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/yourorg/lastmile/api/gen/go/lastmile/v1;lastmilev1'
  _globals['_CREATEUSERREQUEST']._serialized_start=65
  _globals['_CREATEUSERREQUEST']._serialized_end=135
  _globals['_CREATEUSERRESPONSE']._serialized_start=137
  _globals['_CREATEUSERRESPONSE']._serialized_end=190
  _globals['_GETUSERREQUEST']._serialized_start=192
  _globals['_GETUSERREQUEST']._serialized_end=220
  _globals['_GETUSERRESPONSE']._serialized_start=222
  _globals['_GETUSERRESPONSE']._serialized_end=272
  _globals['_AUTHENTICATEREQUEST']._serialized_start=274
  _globals['_AUTHENTICATEREQUEST']._serialized_end=328
  _globals['_AUTHENTICATERESPONSE']._serialized_start=330
  _globals['_AUTHENTICATERESPONSE']._serialized_end=382
  _globals['_USERSERVICE']._serialized_start=385
  _globals['_USERSERVICE']._serialized_end=632
# @@protoc_insertion_point(module_scope)
